import p1 from "../../../assets/image/photo_2019-12-11_16-39-53.jpg";
import p2 from "../../../assets/image/20211216_125938.jpg";
import p3 from "../../../assets/image/20211231_133356.jpg";
import p4 from "../../../assets/image/20220327_113154.jpg";
import p5 from "../../../assets/image/20220327_115051.jpg";
import p6 from "../../../assets/image/20220327_114030.jpg";
import p7 from "../../../assets/image/20220327_122745.jpg";
import p8 from "../../../assets/image/20220327_122718.jpg";
import p9 from "../../../assets/image/20220327_121708.jpg";

const productFilter = [
  {
    id: 1111,
    // category: "کیف_های_چرمی",
    // parent: "کیف_مجلسی_زنانه",
    // parent: 11,
    title: "کیف مجلسی زنانه کد100",
    slug: "کیف_مجلسی_زنانه_کد_100",
    price: "1500000",
    off: "15",
    priceoff: "1200000",
    count: "5",
    material: "چرم گاوی هورس",
    // img: p1,
    color: "قرمز",
    colorValue: "rgb(59, 130, 246)",
    colorcount: "3",
    size: "25 * 28 * 10 ",
    img: p7,
  },
  {
    id: 1112,
    // category: "کیف_های_چرمی",
    // parent: "کیف_مجلسی_زنانه",
    // parent: 11,
    title: "کیف مجلسی زنانه کد100",
    slug: "کیف_مجلسی_زنانه_کد_100",
    price: "1500000",
    off: "15",
    priceoff: "1200000",
    count: "5",
    material: "چرم گاوی هورس",
    // img: p1,
    color: "مشکی",
    colorValue: "rgb(59, 130, 246)",
    colorcount: "3",
    size: "18 * 14 * 9 ",
    img: p2,
  },
  {
    id: 31121,
    // category: "کفش_چرمی",
    // parent1: "کفش_زنانه",
    // parent: "صندل_زنانه",
    title: "صندل زنانه کد601",
    slug: "صندل_زنانه_کد_601",
    price: "800000",
    off: null,
    priceoff: "600000",
    count: "1",
    material: "چرم گاوی لزارد",
    // img: p2,
    color: "قهوه ای",
    colorValue: "#eb3a3a",
    colorcount: "4",
    size: 39,
    img: p2,
  },
  {
    id: 31122,
    // category: "کفش_چرمی",
    // parent1: "کفش_زنانه",
    // parent: "صندل_زنانه",
    title: "صندل زنانه کد601",
    slug: "صندل_زنانه_کد_601",
    price: "800000",
    off: null,
    priceoff: "600000",
    count: "1",
    material: "چرم گاوی لزارد ",
    // img: p2,
    color: "مشکی",
    colorValue: "black",
    colorcount: "8",
    size: 40,
    img: p5,
  },
];

const image = {
  111: [p3, p4, p7, p9],
  231: [p1, p2, p7, p8],
};
const banerImages = [
  { id: 1, img: p2 },
  { id: 2, img: p3 },
  { id: 3, img: p4 },
  { id: 4, img: p7 },
  { id: 5, img: p9 },
];

const imageslider = {
  111: [
    { id: 1, 1111: [p3, p4, p7, p9] },
    { id: 2, 1112: [p1, p2, p5, p6] },
  ],
  231: [
    { id: 3, 2311: [p1, p2, p7, p8] },
    { id: 4, 2312: [p3, p4, p5, p6] },
  ],
  3111: [
    { id: 1, 31111: [p2, p4, p7, p9] },
    { id: 2, 31112: [p3, p4, p7, p9] },
    { id: 3, 31113: [p2, p3, p7, p9] },
    { id: 4, 31114: [p1, p2, p5, p6] },
    { id: 5, 31115: [p1, p2, p7, p8] },
    { id: 6, 31116: [p1, p2, p7, p8] },
    { id: 7, 31117: [p1, p2, p7, p8] },
  ],
  3112: [
    { id: 1, 31121: [p3, p4, p7, p9] },
    { id: 2, 31122: [p3, p5, p8, p9] },
  ],
  431: [
    { id: 1, 4311: [p3, p4, p7, p9] },
    { id: 2, 4312: [p1, p4, p7, p8] },
  ],
  531: [
    { id: 1, 5311: [p2, p4, p7, p9] },
    { id: 2, 5312: [p3, p4, p7, p9] },
    { id: 3, 5313: [p2, p3, p7, p9] },
  ],
  7111: [
    { id: 1, 71111: [p3, p4, p7, p9] },
    { id: 2, 71112: [p3, p4, p8, p9] },
    { id: 3, 71113: [p3, p6, p8, p9] },
  ],
};

//  const imageslider=
//   [
//     {
//       id: 111,
//       attributes: [
//         {
//           id: 1111,
//           images: [p3, p4, p7, p9],
//         },
//         {
//           id: 1112,
//           images: [p1, p2, p5, p6],
//         },
//       ],
//     },
//     {
//       id: 231,
//       attributes: [
//         {
//           id: 2311,
//           images: [p3, p4, p7, p9],
//         },
//         {
//           id: 2312,
//           images: [p1, p2, p5, p6],
//         },
//       ],
//     },
//   ];
// 1111: [p3, p4, p7, p9],
// 1112: [p1, p2, p5, p6],
// 2311: [p1, p2, p7, p8],
// 2312: [p2, p4, p5, p6],
// 4311: [p3, p4, p7, p9],
// 4312: [p1, p4, p7, p8],
// 5311: [p2, p4, p7, p9],
// 5312: [p3, p4, p7, p9],
// 5313: [p2, p3, p7, p9],
// 71111: [p3, p4, p7, p9],
// 71112: [p1, p4, p8, p9],
// 71113: [p3, p6, p8, p9],
// 31121: [p3, p4, p7, p9],
// 31122: [p3, p5, p8, p9],
// };

const color = {
  کیف_های_چرمی: [
    { label: "قرمز", value: "red", countColor: 25 },
    { label: "آبی", value: "blue", countColor: 14 },
    { label: "سفید", value: "white", countColor: 28 },
    { label: "مشکی", value: "black", countColor: 17 },
    { label: "سبز", value: "green", countColor: 23 },
  ],
  کیف_دوشی_زنانه: [
    { label: "قرمز", value: "red", countColor: 16 },
    { label: "آبی", value: "blue", countColor: 9 },
    { label: "سفید", value: "white", countColor: 5 },
  ],
  اکسسوری_چرمی: [
    { label: "قرمز", value: "red", countColor: 24 },
    { label: "صورتی", value: "pink", countColor: 16 },
    { label: "قهوه ای", value: "brown", countColor: 6 },
  ],
  کفش_چرمی: [
    { label: "قرمز", value: "red", countColor: 24 },
    { label: "صورتی", value: "pink", countColor: 16 },
    { label: "قهوه ای", value: "brown", countColor: 6 },
  ],
  پوشاک_چرمی: [
    { label: "قرمز", value: "red", countColor: 15 },
    { label: "آبی", value: "blue", countColor: 8 },
    { label: "سفید", value: "white", countColor: 19 },
  ],
  دکوراسیون_و_منزل: [
    { label: "سفید", value: "white", countColor: 6 },
    { label: "مشکی", value: "black", countColor: 17 },
    { label: "سبز", value: "green", countColor: 9 },
  ],
  محصولات_بچگانه: [
    { label: "قرمز", value: "red", countColor: 10 },
    { label: "صورتی", value: "pink", countColor: 16 },
  ],
  چرم: [
    { label: "قرمز", value: "red", countColor: 21 },
    { label: "آبی", value: "blue", countColor: 9 },
    { label: "سفید", value: "white", countColor: 18 },
    { label: "مشکی", value: "black", countColor: 11 },
    { label: "سبز", value: "green", countColor: 13 },
  ],
};

const size = {
  کیف_های_چرمی: ["25 * 28 * 10 ", "18 *14 *9 "],
  کیف_دوشی_زنانه: ["25 * 28 * 10 ", "18 *14 *9 "],
  اکسسوری_چرمی: ["120 cm * 8 cm", "15 cm * 8 cm * 5 cm"],

  کفش_چرمی: [
    // { id: 1, size: 38 },
    // { id: 2, size: 39 },
    // { id: 3, size: 40 },
    // { id: 4, size: 41 },
    // { id: 5, size: 42 },
    38, 39, 40, 41, 42,
  ],

  پوشاک_چرمی: ["S", "L", "XL"],
  دکوراسیون_و_منزل: ["50 cm * 50 cm"],
  محصولات_بچگانه: ["S", "M"],

  چرم: ["6 foot", "15 foot", "10 foot"],
  "چرم گاوی فلوتر": ["15 foot"],
};
const material = [
  { id: 1, material: "چرم گاوی هورس" },
  { id: 2, material: "چرم گاوی فلوتر" },
  { id: 3, material: "چرم گاوی لزارد" },
  { id: 4, material: "چرم بزی" },
  { id: 5, material: "چرم شترمرغ" },
  { id: 6, material: "چرم مار پیتون" },
  { id: 7, material: "چرم شتر" },
];
const category1 = [
  {
    id: 1,
    slug: "کیف_های_چرمی",
    title: "کیف های چرمی",
    hasChild: 0,
    child: [
      { id: 11, slug: "کیف مجلسی_زنانه", title: "کیف مجلسی زنانه" },
      { id: 12, slug: "کیف_دوشی_چرمی", title: "کیف دوشی چرمی" },
      { id: 13, slug: "کیف مجلسی_زنانه", title: "کیف دستی زنانه" },
      { id: 14, slug: "کیف مجلسی_زنانه", title: "کیف کج یکطرفه" },
      { id: 15, slug: "کیف مجلسی_زنانه", title: "کوله پشتی" },
      { id: 16, slug: "کیف مجلسی_زنانه", title: "کیف پول کتی" },
      { id: 17, slug: "کیف مجلسی_زنانه", title: "کیف پول جیبی مردانه" },
    ],
  },
  {
    id: 3,
    slug: "کفش_چرمی",
    title: "کفش چرمی",
    hasChild: 1,
    child: [
      {
        id: 31,
        slug: "کفش_زنانه",
        title: "کفش زنانه",
        hasChild: 1,
        child: [
          { id: 311, slug: "صندل _زنانه", title: "صندل زنانه" },
          { id: 312, slug: "کفش_مجلسی_زنانه", title: "کفش مجلسی زنانه" },
          { id: 313, slug: "کفش_اسپرت_زنانه", title: "کفش اسپرت زنانه" },
          {
            id: 314,
            slug: "کفش بوت_و_نیم_بوت_زنانه",
            title: "کفش بوت و نیم بوت زنانه",
          },
          { id: 315, slug: "کفش_کالج_زنانه", title: "کفش کالج زنانه" },
        ],
      },
      {
        id: 32,
        slug: "کفش_مردانه",
        title: "کفش مردانه",
        hasChild: 1,
        child: [
          { id: 321, slug: "صندل_مردانه", title: "صندل مردانه" },
          { id: 322, slug: "کفش _مجلسی _مردانه", title: "کفش مجلسی مردانه" },
          { id: 323, slug: "کفش_اسپرت_مردانه", title: "کفش اسپرت مردانه" },
          {
            id: 324,
            slug: "کفش بوت_و_نیم_بوت_مردانه",
            title: "کفش بوت و نیم بوت مردانه",
          },
          { id: 325, slug: "کفش_کالج_مردانه", title: "کفش کالج مردانه" },
        ],
      },
    ],
  },
];
const category = {
  "کیف های چرمی": [
    "کیف مجلسی زنانه",
    "کیف دوشی چرمی",
    "کیف دستی زنانه",
    "کیف کج یکطرفه",
    "کوله پشتی",
    "کیف پول کتی",
    "کیف پول جیبی مردانه",
  ],
  // accesories: [
  "اکسسوری چرمی": [
    "قاب گوشی موبایل",
    "بند ساعت",
    "کمربند چرمی",
    "پیش بند چرمی",
    "گوشواره چرمی",
    "دستبند چرمی",
    "کیف عینک",
  ],
  // kafsh: [
  "کفش چرمی": {
    "کفش زنانه": [
      "صندل زنانه",
      "کفش مجلسی زنانه",
      "کفش اسپرت زنانه",
      "کفش بوت و نیم بوت زنانه",
      "کفش کالج زنانه",
    ],
    "کفش مردانه ": [
      "صندل مردانه",
      "کفش مجلسی مردانه",
      "کفش اسپرت مردانه",
      "کفش بوت و نیم بوت مردانه",
      "کفش کالج مردانه",
    ],
  },
  // // kafshzanane: [
  // "کفش زنانه": [
  // "صندل زنانه",
  // "کفش مجلسی زنانه",
  // "کفش اسپرت زنانه",
  // "کفش بوت و نیم بوت زنانه",
  // "کفش کالج زنانه",
  // ],
  // kafshemardane: [
  // "کفش مردانه": [
  //   "صندل مردانه",
  //   "کفش مجلسی مردانه",
  //   "کفش اسپرت مردانه",
  //   "کفش بوت و نیم بوت مردانه",
  //   "کفش کالج مردانه",
  // ],
  // poshak: [
  "پوشاک چرمی": ["دستکش چرمی", "لباس چرمی", "کلاه چرمی"],
  // dekor: [
  "دکوراسیون و منزل": ["تابلو چرمی", "فرش چرمی", "کوسن چرمی"],
  // children: [
  "محصولات بچگانه": ["کوله پشتی بچگانه"],
  // charm: [
  چرم: {
    "چرم گاوی": ["چرم گاوی فلوتر", "چرم گاوی هورس", "چرم گاوی لزارد"],
    //  "چرم بزی", "چرم شتر", "چرم مار پیتون", "چرم شترمرغ"
  },
  // charmegavi: [
  // "چرم گاوی": ["چرم گاوی فلوتر", "چرم گاوی هورس", "چرم گاوی لزارد"],
};

const child3 = [
  {
    id: 111,
    category: "کیف_های_چرمی",
    categoryId: 1,
    parent: "کیف_مجلسی_زنانه",
    parentId: 11,
    // parent: 11,
    title: "کیف مجلسی زنانه کد100",
    slug: "کیف_مجلسی_زنانه_کد_100",
    price: "1500000",
    off: "15",
    priceoff: "1200000",
    count: "5",
    material: "چرم گاوی هورس",
    img: p1,
    length: "25cm",
    height: "28cm",
    width: "10cm",
    insertdate: "1402/04/01",
    attributes: [
      {
        id: 1111,
        color: "قرمز",
        colorValue: "rgb(59, 130, 246)",
        colorcount: "3",
        sizelist: [
          { id: 1, size: "25 * 28 * 10" },
          // { id: 2, size:  "24 * 25 * 10 " },
          // { id: 3, size:  "20 * 25 * 10 " },
        ],
        img: p7,
      },
      {
        id: 1112,
        color: "مشکی",
        colorValue: "black",
        colorcount: "2",
        sizelist: [
          { id: 25, size: "18 * 14 * 9" },
          // { id: 35, size: 41 },
        ],
        img: p2,
      },
    ],
  },
  {
    id: 112,
    category: "کیف_های_چرمی",
    parent: "کیف_مجلسی_زنانه",
    title: " کیف مجلسی زنانه کد101",
    slug: "کیف_مجلسی_زنانه_کد_101",
    price: "800000",
    off: "5",
    priceoff: "700000",
    count: "8",
    length: "20cm",
    height: "25cm",
    width: "12cm",
    material: "چرم شتر",
    img: p4,
    attributes: [
      {
        id: 1121,
        color: "سبز",
        colorValue: "green",
        colorcount: "6",
        sizelist: [
          { id: 17, size: "20 * 15 * 8 " },
          // { id: 27, size:  "18 * 14 * 9 " },
          // { id: 37, size:  "20 * 14 * 6 " },
        ],
        img: p3,
      },
      {
        id: 1122,
        color: "زرد",
        colorValue: "yellow",
        colorcount: "3",
        sizelist: [
          // { id: 16, size:  "25 * 28 * 10 " },
          // { id: 26, size:"20 * 14 * 6 " },
          { id: 36, size: "18 * 14 * 9 " },
        ],
        img: p5,
      },
    ],
  },
  {
    id: 121,
    category: "کیف_های_چرمی",
    parent: "کیف_دوشی_زنانه",
    title: "کیف دوشی زنانه کد200",
    slug: "کیف_دوشی_زنانه_کد200",
    price: "1800000",
    off: "10",
    priceoff: "1000000",
    count: "4",
    length: "25cm",
    height: "28cm",
    width: "10cm",
    material: "چرم گاوی فلوتر",
    img: p1,
    attributes: [
      {
        id: 1211,
        color: "مشکی",
        colorValue: "black",
        colorcount: "2",
        sizelist: [
          { id: 17, size: "30 * 29 * 10 " },
          // { id: 27, size:  "26 * 28 * 10 " },
          // { id: 37, size:  "25 * 29 * 9 " },
        ],
        img: p2,
      },
      {
        id: 1212,
        color: "سبز",
        colorValue: "green",
        colorcount: "6",
        sizelist: [
          { id: 17, size: "28 * 24 * 9 " },
          // { id: 27, size: 40 },
          // { id: 37, size: 41 },
        ],
        img: p1,
      },
    ],
  },
  {
    id: 161,
    category: "کیف_های_چرمی",
    parent: "کیف_پول_کتی",
    title: "کیف پول کتی کد300",
    slug: "کیف_پول_کتی_کد_300",
    price: "900000",
    off: null,
    priceoff: "700000",
    count: 10,
    length: "25cm",
    height: "28cm",
    width: "10cm",
    material: "چرم بزی",
    img: p1,
    attributes: [
      {
        id: 1611,
        color: "قهوه ای",
        colorValue: "brown",
        colorcount: 12,
        sizelist: [
          { id: 18, size: "20*10 " },
          // { id: 28, size: 40 },
          // { id: 38, size: 41 },
        ],
        img: p1,
      },
      {
        id: 1612,
        color: "زرشکی",
        colorValue: "#eb3a3a",
        colorcount: "1",
        sizelist: [
          { id: 15, size: "22 * 11 " },
          // { id: 25, size: 40 },
          // { id: 35, size: 41 },
          // { id: 45, size: 42 },
        ],
        img: p1,
      },
      {
        id: 1613,
        color: "آبی",
        colorValue: "blue",
        colorcount: null,
        sizelist: [
          { id: 14, size: "22 * 11 " },
          // { id: 24, size: 40 },
          // { id: 34, size: 41 },
        ],
        img: p1,
      },
    ],
  },
  {
    id: 211,
    category: "اکسسوری_چرمی",
    parent: "قاب_گوشی_موبایل",
    title: "قاب گوشی موبایل کد_500",
    slug: "قاب_گوشی_موبایل_کد_500",
    price: "500000",
    off: "10",
    priceoff: "400000",
    count: "8",
    length: "8cm",
    height: "15cm",
    width: "5cm",
    material: "چرم شترمرغ",
    img: p8,
    attributes: [
      {
        id: 2111,
        color: "قهوه ای",
        colorValue: "blue",
        colorcount: 12,
        sizelist: [
          { id: 18, size: "14 * 9 " },
          { id: 28, size: "12 * 8 " },
          { id: 38, size: "13 * 9 " },
        ],
        img: p1,
      },
      {
        id: 2112,
        color: "زرشکی",
        colorValue: "#eb3a3a",
        colorcount: "1",
        sizelist: [
          { id: 18, size: "14 * 9 " },
          { id: 28, size: "12 * 8 " },
          { id: 38, size: "13 * 9 " },
          { id: 45, size: "12 * 6" },
        ],
        img: p1,
      },
      {
        id: 2113,
        color: "آبی",
        colorValue: "white",
        colorcount: null,
        sizelist: [
          { id: 28, size: "12 * 8 " },
          { id: 38, size: "13 * 9 " },
          { id: 45, size: "12 * 6" },
        ],
        img: p1,
      },
    ],
  },

  {
    id: 231,
    category: "اکسسوری_چرمی",
    parent: "کمربند_چرمی",
    title: " کمربند چرمی کد_400",
    slug: "کمربند_چرمی_کد_400",
    size: "120cm",
    price: "1500000",
    off: null,
    priceoff: "1200000",
    count: "8",
    length: "105cm",
    width: "10cm",
    material: "چرم مار پیتون",
    img: p5,
    attributes: [
      {
        id: 2311,
        color: "قرمز",
        colorValue: "yellow",
        colorcount: null,
        sizelist: [
          { id: 16, size: "120 cm * 10 cm" },
          // { id: 26, size: "110 * 10" },
          // { id: 36, size: "105 * 8" },
        ],
        img: p4,
      },
      {
        id: 2312,
        color: "مشکی",
        colorValue: "black",
        colorcount: null,
        sizelist: [{ id: 26, size: "110 cm * 10 cm" }],
        img: p9,
      },
    ],
  },
  {
    id: 3111,
    category: "کفش_چرمی",
    categoryId: 3,
    parent1: "کفش_زنانه",
    parent1Id: 31,
    parent: "صندل_زنانه",
    parentId: 311,
    title: "صندل زنانه کد600",
    slug: "صندل_زنانه_کد_600",
    size: "38",
    price: "700000",
    off: "20",
    priceoff: "500000",
    count: "0",
    material: "چرم گاوی لزارد",
    img: p1,
    attributes: [
      {
        id: 31111,
        color: "سبز",
        colorValue: "#eb3a3a",
        colorcount: "5",
        sizelist: [
          { id: 1, size: 39 },
          { id: 2, size: 40 },
          { id: 3, size: 41 },
        ],
        img: p1,
      },
      {
        id: 31112,
        color: "کرم",
        colorValue: "green",
        colorcount: "4",
        sizelist: [
          { id: 11, size: 39 },
          { id: 22, size: 40 },
          { id: 33, size: 41 },
        ],
        img: p1,
      },
      {
        id: 31113,
        color: "قرمز",
        colorValue: "yellow",
        colorcount: "3",
        sizelist: [
          { id: 16, size: 39 },
          { id: 26, size: 40 },
          { id: 36, size: 41 },
        ],
        img: p1,
      },
      {
        id: 31114,
        color: "مشکی",
        colorValue: "black",
        colorcount: "2",
        sizelist: [
          { id: 17, size: 39 },
          { id: 27, size: 40 },
          { id: 37, size: 41 },
        ],
        img: p1,
      },
      {
        id: 31115,
        color: "قهوه ای",
        colorValue: "blue",
        colorcount: 12,
        sizelist: [
          { id: 18, size: 39 },
          { id: 28, size: 40 },
          { id: 38, size: 41 },
        ],
        img: p1,
      },
      {
        id: 31116,
        color: "زرشکی",
        colorValue: "#eb3a3a",
        colorcount: "1",
        sizelist: [
          { id: 15, size: 38 },
          { id: 25, size: 40 },
          { id: 35, size: 41 },
          { id: 45, size: 42 },
        ],
        img: p1,
      },
      {
        id: 31117,
        color: "سفید",
        colorValue: "white",
        colorcount: null,
        sizelist: [
          { id: 14, size: 39 },
          { id: 24, size: 40 },
          { id: 34, size: 41 },
        ],
        img: p1,
      },
    ],
  },
  {
    id: 3141,
    category: "کفش_چرمی",
    parent1: "کفش_زنانه",
    parent: "کفش_بوت_نیم_بوت_زنانه",
    title: "کفش بوت و نیم بوت زنانه کد620",
    slug: "کفش_بوت_نیم_بوت_زنانه_کد_620",
    size: "39",
    price: "800000",
    off: null,
    priceoff: "500000",
    count: "0",
    material: "چرم گاوی هورس",
    img: p3,
    attributes: [
      {
        id: 31411,
        color: "قهوه ای",
        colorValue: "blue",
        colorcount: 12,
        sizelist: [
          { id: 18, size: 39 },
          { id: 28, size: 40 },
          { id: 38, size: 41 },
        ],
        img: p1,
      },
      {
        id: 31412,
        color: "زرشکی",
        colorValue: "#eb3a3a",
        colorcount: "1",
        sizelist: [
          { id: 15, size: 38 },
          { id: 25, size: 40 },
          { id: 35, size: 41 },
          { id: 45, size: 42 },
        ],
        img: p1,
      },
      {
        id: 31413,
        color: "آبی",
        colorValue: "white",
        colorcount: null,
        sizelist: [
          { id: 14, size: 39 },
          { id: 24, size: 40 },
          { id: 34, size: 41 },
        ],
        img: p1,
      },
    ],
  },
  {
    id: 3142,
    category: "کفش_چرمی",
    parent1: "کفش_زنانه",
    parent: "کفش_بوت_نیم_بوت_زنانه",
    title: "کفش بوت و نیم بوت زنانه کد621",
    slug: "کفش_بوت_نیم_بوت_زنانه_کد_621",
    size: "39",
    price: "1300000",
    off: 20,
    priceoff: "500000",
    count: "0",
    material: "چرم گاوی هورس",
    img: p3,
    attributes: [
      {
        id: 31411,
        color: "قهوه ای",
        colorValue: "blue",
        colorcount: 12,
        sizelist: [
          { id: 18, size: 39 },
          { id: 28, size: 40 },
          { id: 38, size: 41 },
        ],
        img: p1,
      },
      {
        id: 31412,
        color: "زرشکی",
        colorValue: "#eb3a3a",
        colorcount: "1",
        sizelist: [
          { id: 15, size: 38 },
          { id: 25, size: 40 },
          { id: 35, size: 41 },
          { id: 45, size: 42 },
        ],
        img: p1,
      },
    ],
  },
  {
    id: 3143,
    category: "کفش_چرمی",
    parent1: "کفش_زنانه",
    parent: "کفش_بوت_نیم_بوت_زنانه",
    title: "کفش بوت و نیم بوت زنانه کد623",
    slug: "کفش_بوت_نیم_بوت_زنانه_کد_623",
    size: "39",
    price: "1500000",
    off: 10,
    priceoff: "500000",
    count: "0",
    material: "چرم گاوی هورس",
    img: p3,
    attributes: [
      {
        id: 31411,
        color: "قهوه ای",
        colorValue: "blue",
        colorcount: 12,
        sizelist: [
          { id: 18, size: 39 },
          { id: 28, size: 40 },
          { id: 38, size: 41 },
        ],
        img: p1,
      },
      {
        id: 31412,
        color: "زرشکی",
        colorValue: "#eb3a3a",
        colorcount: "1",
        sizelist: [
          { id: 15, size: 38 },
          { id: 25, size: 40 },
          { id: 35, size: 41 },
          { id: 45, size: 42 },
        ],
        img: p1,
      },
    ],
  },
  {
    id: 3151,
    category: "کفش_چرمی",
    parent1: "کفش_زنانه",
    parent: "کفش_کالج_زنانه",
    title: "کفش کالج زنانه کد630",
    slug: "کفش_کالج_زنانه_کد_630",
    size: "39",
    price: "800000",
    off: "26",
    priceoff: "500000",
    count: "0",
    material: "چرم گاوی هورس",
    img: p5,
    attributes: [
      {
        id: 31511,
        color: "قهوه ای",
        colorValue: "blue",
        colorcount: 12,
        sizelist: [
          { id: 18, size: 39 },
          { id: 28, size: 40 },
          { id: 38, size: 41 },
        ],
        img: p1,
      },
      {
        id: 31512,
        color: "زرشکی",
        colorValue: "#eb3a3a",
        colorcount: "1",
        sizelist: [
          { id: 15, size: 38 },
          { id: 25, size: 40 },
          { id: 35, size: 41 },
          { id: 45, size: 42 },
        ],
        img: p1,
      },
      {
        id: 31513,
        color: "آبی",
        colorValue: "white",
        colorcount: null,
        sizelist: [
          { id: 14, size: 39 },
          { id: 24, size: 40 },
          { id: 34, size: 41 },
        ],
        img: p1,
      },
    ],
  },
  {
    id: 3152,
    category: "کفش_چرمی",
    parent1: "کفش_زنانه",
    parent: "کفش_کالج_زنانه",
    title: "کفش کالج زنانه کد631",
    slug: "کفش_کالج_زنانه_کد_631",
    size: "39",
    price: "700000",
    off: "26",
    priceoff: "500000",
    count: "0",
    material: "چرم گاوی هورس",
    img: p5,
    attributes: [
      {
        id: 31511,
        color: "قهوه ای",
        colorValue: "blue",
        colorcount: 12,
        sizelist: [
          { id: 18, size: 39 },
          { id: 28, size: 40 },
          { id: 38, size: 41 },
        ],
        img: p1,
      },
      {
        id: 31512,
        color: "زرشکی",
        colorValue: "#eb3a3a",
        colorcount: "1",
        sizelist: [
          { id: 15, size: 38 },
          { id: 25, size: 40 },
          { id: 35, size: 41 },
          { id: 45, size: 42 },
        ],
        img: p1,
      },
    ],
  },
  {
    id: 3153,
    category: "کفش_چرمی",
    parent1: "کفش_زنانه",
    parent: "کفش_کالج_زنانه",
    title: "کفش کالج زنانه کد640",
    slug: "کفش_کالج_زنانه_کد_640",
    size: "39",
    price: "1200000",
    off: "26",
    priceoff: "500000",
    count: "0",
    material: "چرم گاوی هورس",
    img: p5,
    attributes: [
      {
        id: 31511,
        color: "قهوه ای",
        colorValue: "blue",
        colorcount: 12,
        sizelist: [
          { id: 18, size: 39 },
          { id: 28, size: 40 },
          { id: 38, size: 41 },
        ],
        img: p1,
      },
      {
        id: 31512,
        color: "زرشکی",
        colorValue: "#eb3a3a",
        colorcount: "1",
        sizelist: [
          { id: 15, size: 38 },
          { id: 25, size: 40 },
          { id: 35, size: 41 },
          { id: 45, size: 42 },
        ],
        img: p1,
      },
    ],
  },
  {
    id: 3112,
    category: "کفش_چرمی",
    parent1: "کفش_زنانه",
    parent: "صندل_زنانه",
    title: "صندل زنانه کد601",
    slug: "صندل_زنانه_کد_601",
    size: "39",
    price: "800000",
    off: null,
    priceoff: "600000",
    count: "1",
    material: "چرم گاوی لزارد",
    img: p2,
    attributes: [
      {
        id: 31121,
        color: "قهوه ای",
        colorValue: "#eb3a3a",
        colorcount: "4",
        sizelist: [
          { id: 19, size: 39 },
          { id: 29, size: 40 },
          { id: 39, size: 41 },
        ],
        img: p2,
      },
      {
        id: 31122,
        color: "مشکی",
        colorValue: "black",
        colorcount: "8",
        sizelist: [
          { id: 81, size: 39 },
          { id: 92, size: 40 },
          { id: 93, size: 41 },
        ],
        img: p5,
      },
    ],
  },
  {
    id: 3231,
    category: "کفش_چرمی",
    parent1: "کفش_مردانه",
    parent: "کفش_اسپرت_مردانه",
    title: "کفش اسپرت مردانه کد605",
    slug: "کفش_اسپرت_مردانه_کد_605",
    size: "39",
    price: "800000",
    off: "25",
    priceoff: "500000",
    count: "0",
    material: "چرم گاوی هورس",
    img: p8,
    attributes: [
      {
        id: 32311,
        color: "کرم",
        colorValue: "#eb3a3a",
        colorcount: "7",
        sizelist: [
          { id: 61, size: 39 },
          { id: 62, size: 40 },
          { id: 63, size: 41 },
        ],
        img: p3,
      },
      {
        id: 32312,
        color: "صورتی",
        colorValue: "pink",
        colorcount: "3",
        sizelist: [
          { id: 41, size: 39 },
          { id: 42, size: 40 },
          { id: 43, size: 41 },
        ],
        img: p3,
      },
    ],
  },

  {
    id: 431,
    category: "پوشاک_چرمی",
    parent: "کلاه_چرمی",
    title: "کلاه چرمی کد700",
    slug: "کلاه_چرمی_کد_700",
    size: "xl",
    price: "300000",
    off: "15",
    priceoff: "200000",
    count: "0",
    material: "چرم بزی",
    img: p6,
    attributes: [
      {
        id: 4311,
        color: "قرمز",
        colorValue: "yellow",
        colorcount: "3",
        sizelist: [
          { id: 16, size: "L" },
          { id: 26, size: "XL" },
          { id: 36, size: "S" },
        ],
        img: p1,
      },
      {
        id: 4312,
        color: "مشکی",
        colorValue: "black",
        colorcount: "2",
        sizelist: [
          { id: 26, size: "XL" },
          { id: 36, size: "S" },
          { id: 46, size: "L" },
          { id: 56, size: "M" },
        ],
        img: p1,
      },
    ],
  },

  {
    id: 531,
    category: "دکوراسیون_و_منزل",
    parent: "کوسن_چرمی",
    title: "کوسن چرمی کد800",
    slug: "کوسن_چرمی_کد_800",
    price: "400000",
    off: "25",
    priceoff: "300000",
    count: "1",
    length: "25cm",
    height: "28cm",
    width: "10cm",
    material: "چرم شتر",
    img: p7,
    attributes: [
      {
        id: 5311,
        color: "کرم",
        colorValue: "#eb3a3a",
        colorcount: "7",
        sizelist: [{ id: 61, size: "40 * 50" }],
        img: p3,
      },
      {
        id: 5312,
        color: "صورتی",
        colorValue: "pink",
        colorcount: "3",
        sizelist: [{ id: 61, size: "60 * 50" }],
        img: p3,
      },
      {
        id: 5313,
        color: "مشکی",
        colorValue: "black",
        colorcount: "2",
        sizelist: [{ id: 61, size: "50 * 50" }],
        img: p1,
      },
    ],
  },

  {
    id: 7111,
    category: "چرم",
    parent1: "چرم_گاوی",
    parent: "چرم_گاوی_فلوتر",
    title: "چرم گاوی فلوتر کد1000",
    slug: "چرم_گاوی_فلوتر_کد1000",
    size: "6foot",
    price: "60000",
    off: null,
    priceoff: "45000",
    count: "2",
    material: "چرم گاوی فلوتر",
    img: p8,
    attributes: [
      {
        id: 71111,
        color: "کرم",
        colorValue: "#eb3a3a",
        colorcount: "7",
        sizelist: [{ id: 61, size: "15 foot" }],
        img: p3,
      },
      {
        id: 71112,
        color: "صورتی",
        colorValue: "pink",
        colorcount: "3",
        sizelist: [{ id: 61, size: "15 foot " }],
        img: p3,
      },
      {
        id: 71113,
        color: "مشکی",
        colorValue: "black",
        colorcount: "2",
        sizelist: [{ id: 61, size: "15 foot " }],
        img: p1,
      },
    ],
  },
];

const child2 = [
  {
    id: 311,
    title: "صندل زنانه",
    slug: "صندل_زنانه",
    href: "./Content.js",
    child: child3,
  },
  {
    id: 323,
    title: "کفش اسپرت مردانه",
    slug: "کفش_اسپرت_مردانه",
    href: "./Content.js",
    type: 0,
    child: child3,
  },
];
const child1 = [
  {
    id: 11,
    title: "کیف مجلسی زنانه",
    slug: "کیف_مجلسی_زنانه",
    // slugd: "کیف_مجلسی_زنانه_کد_100",
    category: "کیف_چرمی",
    href: "./Content.js",
    type: 0,
    childs: 111,
    parent: 1,
    child: child3,
  },
  {
    id: 31,
    title: "کفش زنانه",
    slug: "کفش_زنانه",
    category: "کفش_چرمی",
    child: child2,
  },
  {
    id: 32,
    title: "کفش مردانه",
    slug: "کفش_مردانه",
    category: "کفش_چرمی",
    child: child2,
  },
];

const productslist2 = [
  {
    id: 1,
    title: "کیف های چرمی",
    slug: "کیف_های_چرمی",
    childs: 11,
    parent: 0,
    child: child1,
  },
  {
    id: 3,
    title: "کفش چرمی",
    slug: "کفش_چرمی",
    category: "کفش_چرمی",
    child: child1,
  },
  {
    id: 2,
    title: "اکسسوری چرمی",
    slug: "اکسسوری_چرمی",
    category: "اکسسوری چرمی",
    // pic: accesorie,
    child: child1,
  },
  {
    id: 4,
    title: "پوشاک چرمی",
    slug: "پوشاک_چرمی",
    // pic: clothes,
    child: child1,
  },
  {
    id: 5,
    title: "دکوراسیون و منزل",
    slug: "دکوراسیون_و_منزل",
    child: child1,
  },
  {
    id: 6,
    title: "محصولات بچگانه",
    slug: "محصولات_بچگانه",
    child: child1,
  },
  {
    id: 7,
    title: "چرم",
    slug: "چرم",
    // pic: charm,
    child: child1,
  },
];

export {
  productslist2,
  child1,
  child2,
  child3,
  category,
  category1,
  material,
  size,
  color,
  imageslider,
  image,
  productFilter,
  banerImages,
};
